spring:
  datasource:
    url: jdbc:mysql://localhost:3306/deliverium
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    properties:
      hibernate:
        ddl-auto: update
server:
  servlet:
    session:
      timeout: 30m
